import {Armor} from './armor.model';
import {ArmorLocation, ArmorProtection, ArmorType} from './armor.enum';

export const ProtectionValue = {
  [ArmorType.Cloth]: {
    [ArmorProtection.Blunt]: 1,
    [ArmorProtection.Edge]: 1,
    [ArmorProtection.Pierce]: 1,
    [ArmorProtection.Fire]: 1,
  },
  [ArmorType.Quilt]: {
    [ArmorProtection.Blunt]: 5,
    [ArmorProtection.Edge]: 3,
    [ArmorProtection.Pierce]: 2,
    [ArmorProtection.Fire]: 4,
  },
  [ArmorType.Leather]: {
    [ArmorProtection.Blunt]: 2,
    [ArmorProtection.Edge]: 4,
    [ArmorProtection.Pierce]: 3,
    [ArmorProtection.Fire]: 3,
  },
  [ArmorType.Kurbul]: {
    [ArmorProtection.Blunt]: 4,
    [ArmorProtection.Edge]: 5,
    [ArmorProtection.Pierce]: 4,
    [ArmorProtection.Fire]: 3,
  },
  [ArmorType.Ring]: {
    [ArmorProtection.Blunt]: 3,
    [ArmorProtection.Edge]: 6,
    [ArmorProtection.Pierce]: 4,
    [ArmorProtection.Fire]: 3,
  },
  [ArmorType.Mail]: {
    [ArmorProtection.Blunt]: 2,
    [ArmorProtection.Edge]: 8,
    [ArmorProtection.Pierce]: 5,
    [ArmorProtection.Fire]: 1,
  },
  [ArmorType.Scale]: {
    [ArmorProtection.Blunt]: 5,
    [ArmorProtection.Edge]: 9,
    [ArmorProtection.Pierce]: 4,
    [ArmorProtection.Fire]: 5,
  },
  [ArmorType.Plate]: {
    [ArmorProtection.Blunt]: 6,
    [ArmorProtection.Edge]: 10,
    [ArmorProtection.Pierce]: 6,
    [ArmorProtection.Fire]: 2,
  },
};

export const ArmorList: Armor[] = [
  {
    name: 'cloth cap',
    type: ArmorType.Cloth,
    coverage: {
      [ArmorLocation.Skull]: true,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 0.4,
    basePrice: 8
  },
  {
    name: 'cloth hood',
    type: ArmorType.Cloth,
    coverage: {
      [ArmorLocation.Skull]: true,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: true,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 0.8,
    basePrice: 16
  },
  {
    name: 'cloth leggings',
    type: ArmorType.Cloth,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: true,
      [ArmorLocation.Groin]: true,
      [ArmorLocation.Thighs]: true,
      [ArmorLocation.Knees]: true,
      [ArmorLocation.Calves]: true,
      [ArmorLocation.Feet]: true,
    }, baseWeight: 4.4,
    basePrice: 88
  },
  {
    name: 'cloth robe',
    type: ArmorType.Cloth,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: true,
      [ArmorLocation.UpperArms]: true,
      [ArmorLocation.Elbows]: true,
      [ArmorLocation.Forearms]: true,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: true,
      [ArmorLocation.ThoraxBack]: true,
      [ArmorLocation.AbdomenFront]: true,
      [ArmorLocation.AbdomenBack]: true,
      [ArmorLocation.Hips]: true,
      [ArmorLocation.Groin]: true,
      [ArmorLocation.Thighs]: true,
      [ArmorLocation.Knees]: true,
      [ArmorLocation.Calves]: true,
      [ArmorLocation.Feet]: false
    }, baseWeight: 7.9,
    basePrice: 158
  },
  {
    name: 'cloth surcoat',
    type: ArmorType.Cloth,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: true,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: true,
      [ArmorLocation.ThoraxBack]: true,
      [ArmorLocation.AbdomenFront]: true,
      [ArmorLocation.AbdomenBack]: true,
      [ArmorLocation.Hips]: true,
      [ArmorLocation.Groin]: true,
      [ArmorLocation.Thighs]: true,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 5.3,
    basePrice: 106
  },
  {
    name: 'cloth tunic',
    type: ArmorType.Cloth,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: true,
      [ArmorLocation.UpperArms]: true,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: true,
      [ArmorLocation.ThoraxBack]: true,
      [ArmorLocation.AbdomenFront]: true,
      [ArmorLocation.AbdomenBack]: true,
      [ArmorLocation.Hips]: true,
      [ArmorLocation.Groin]: true,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 4.4,
    basePrice: 88
  },
  {
    name: 'cloth vest',
    type: ArmorType.Cloth,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: true,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: true,
      [ArmorLocation.ThoraxBack]: true,
      [ArmorLocation.AbdomenFront]: true,
      [ArmorLocation.AbdomenBack]: true,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 2.8,
    basePrice: 56
  },
  {
    name: 'quilt cap',
    type: ArmorType.Quilt,
    coverage: {
      [ArmorLocation.Skull]: true,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 1.2,
    basePrice: 16
  },
  {
    name: 'quilt cowl',
    type: ArmorType.Quilt,
    coverage: {
      [ArmorLocation.Skull]: true,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: true,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 2.4,
    basePrice: 32
  },
  {
    name: 'quilt gambeson',
    type: ArmorType.Quilt,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: true,
      [ArmorLocation.UpperArms]: true,
      [ArmorLocation.Elbows]: true,
      [ArmorLocation.Forearms]: true,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: true,
      [ArmorLocation.ThoraxBack]: true,
      [ArmorLocation.AbdomenFront]: true,
      [ArmorLocation.AbdomenBack]: true,
      [ArmorLocation.Hips]: true,
      [ArmorLocation.Groin]: true,
      [ArmorLocation.Thighs]: true,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 19.8,
    basePrice: 264
  },
  {
    name: 'quilt leggings',
    type: ArmorType.Quilt,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: true,
      [ArmorLocation.Groin]: true,
      [ArmorLocation.Thighs]: true,
      [ArmorLocation.Knees]: true,
      [ArmorLocation.Calves]: true,
      [ArmorLocation.Feet]: true,
    }, baseWeight: 13.2,
    basePrice: 176
  },
  {
    name: 'quilt tunic',
    type: ArmorType.Quilt,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: true,
      [ArmorLocation.UpperArms]: true,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: true,
      [ArmorLocation.ThoraxBack]: true,
      [ArmorLocation.AbdomenFront]: true,
      [ArmorLocation.AbdomenBack]: true,
      [ArmorLocation.Hips]: true,
      [ArmorLocation.Groin]: true,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 13.2,
    basePrice: 176
  },
  {
    name: 'leather calftboots',
    type: ArmorType.Leather,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: true,
      [ArmorLocation.Feet]: true,
    }, baseWeight: 3.2,
    basePrice: 64
  },
  {
    name: 'leather cap',
    type: ArmorType.Leather,
    coverage: {
      [ArmorLocation.Skull]: true,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 0.8,
    basePrice: 16
  },
  {
    name: 'leather cowl',
    type: ArmorType.Leather,
    coverage: {
      [ArmorLocation.Skull]: true,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: true,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 1.6,
    basePrice: 32
  },
  {
    name: 'leather gauntlets',
    type: ArmorType.Leather,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: true,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 0.8,
    basePrice: 16
  },
  {
    name: 'leather kneeboots',
    type: ArmorType.Leather,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: true,
      [ArmorLocation.Calves]: true,
      [ArmorLocation.Feet]: true,
    }, baseWeight: 3.8,
    basePrice: 76
  },
  {
    name: 'leather leggings',
    type: ArmorType.Leather,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: true,
      [ArmorLocation.Groin]: true,
      [ArmorLocation.Thighs]: true,
      [ArmorLocation.Knees]: true,
      [ArmorLocation.Calves]: true,
      [ArmorLocation.Feet]: true,
    }, baseWeight: 8.8,
    basePrice: 176
  },
  {
    name: 'leather shoes',
    type: ArmorType.Leather,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: true,
    }, baseWeight: 1.2,
    basePrice: 24
  },
  {
    name: 'leather surcoat',
    type: ArmorType.Leather,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: true,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: true,
      [ArmorLocation.ThoraxBack]: true,
      [ArmorLocation.AbdomenFront]: true,
      [ArmorLocation.AbdomenBack]: true,
      [ArmorLocation.Hips]: true,
      [ArmorLocation.Groin]: true,
      [ArmorLocation.Thighs]: true,
      [ArmorLocation.Knees]: true,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 11.2,
    basePrice: 224
  },
  {
    name: 'leather tunic',
    type: ArmorType.Leather,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: true,
      [ArmorLocation.UpperArms]: true,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: true,
      [ArmorLocation.ThoraxBack]: true,
      [ArmorLocation.AbdomenFront]: true,
      [ArmorLocation.AbdomenBack]: true,
      [ArmorLocation.Hips]: true,
      [ArmorLocation.Groin]: true,
      [ArmorLocation.Thighs]: true,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 11.8,
    basePrice: 236
  },
  {
    name: 'leather vest',
    type: ArmorType.Leather,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: true,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: true,
      [ArmorLocation.ThoraxBack]: true,
      [ArmorLocation.AbdomenFront]: true,
      [ArmorLocation.AbdomenBack]: true,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 5.6,
    basePrice: 112
  },
  {
    name: 'kurbul ailettes',
    type: ArmorType.Kurbul,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: true,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 1.0,
    basePrice: 20
  },
  {
    name: 'kurbul breastplate',
    type: ArmorType.Kurbul,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: true,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: true,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 3.0,
    basePrice: 60
  },
  {
    name: 'kurbul backplate',
    type: ArmorType.Kurbul,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: true,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: true,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 3.0,
    basePrice: 60
  },
  {
    name: 'kurbul coudes',
    type: ArmorType.Kurbul,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: true,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 0.5,
    basePrice: 10
  },
  {
    name: 'kurbul greaves',
    type: ArmorType.Kurbul,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: true,
      [ArmorLocation.Feet]: false
    }, baseWeight: 2.5,
    basePrice: 50
  },
  {
    name: 'kurbul halfhelm',
    type: ArmorType.Kurbul,
    coverage: {
      [ArmorLocation.Skull]: true,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 1.0,
    basePrice: 20
  },
  {
    name: 'kurbul kneecops',
    type: ArmorType.Kurbul,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: true,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 0.8,
    basePrice: 15
  },
  {
    name: 'kurbul rerebraces',
    type: ArmorType.Kurbul,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: true,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 1.5,
    basePrice: 30
  },
  {
    name: 'kurbul vambraces',
    type: ArmorType.Kurbul,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: true,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 1.3,
    basePrice: 25
  },
  {
    name: 'ring byrnie',
    type: ArmorType.Ring,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: true,
      [ArmorLocation.UpperArms]: true,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: true,
      [ArmorLocation.ThoraxBack]: true,
      [ArmorLocation.AbdomenFront]: true,
      [ArmorLocation.AbdomenBack]: true,
      [ArmorLocation.Hips]: true,
      [ArmorLocation.Groin]: true,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 17.6,
    basePrice: 308
  },
  {
    name: 'ring gauntlets',
    type: ArmorType.Ring,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: true,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 1.6,
    basePrice: 28
  },
  {
    name: 'ring halfhelm',
    type: ArmorType.Ring,
    coverage: {
      [ArmorLocation.Skull]: true,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 1.6,
    basePrice: 28
  },
  {
    name: 'ring hauberk',
    type: ArmorType.Ring,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: true,
      [ArmorLocation.UpperArms]: true,
      [ArmorLocation.Elbows]: true,
      [ArmorLocation.Forearms]: true,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: true,
      [ArmorLocation.ThoraxBack]: true,
      [ArmorLocation.AbdomenFront]: true,
      [ArmorLocation.AbdomenBack]: true,
      [ArmorLocation.Hips]: true,
      [ArmorLocation.Groin]: true,
      [ArmorLocation.Thighs]: true,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 26.4,
    basePrice: 462
  },
  {
    name: 'ring leggings',
    type: ArmorType.Ring,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: true,
      [ArmorLocation.Groin]: true,
      [ArmorLocation.Thighs]: true,
      [ArmorLocation.Knees]: true,
      [ArmorLocation.Calves]: true,
      [ArmorLocation.Feet]: true,
    }, baseWeight: 17.6,
    basePrice: 308
  },
  {
    name: 'ring vest',
    type: ArmorType.Ring,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: true,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: true,
      [ArmorLocation.ThoraxBack]: true,
      [ArmorLocation.AbdomenFront]: true,
      [ArmorLocation.AbdomenBack]: true,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 11.2,
    basePrice: 196
  },
  {
    name: 'mail byrnie',
    type: ArmorType.Mail,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: true,
      [ArmorLocation.UpperArms]: true,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: true,
      [ArmorLocation.ThoraxBack]: true,
      [ArmorLocation.AbdomenFront]: true,
      [ArmorLocation.AbdomenBack]: true,
      [ArmorLocation.Hips]: true,
      [ArmorLocation.Groin]: true,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 22.0,
    basePrice: 660
  },
  {
    name: 'mail cowl',
    type: ArmorType.Mail,
    coverage: {
      [ArmorLocation.Skull]: true,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: true,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 4.0,
    basePrice: 120
  },
  {
    name: 'mail hauberk',
    type: ArmorType.Mail,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: true,
      [ArmorLocation.UpperArms]: true,
      [ArmorLocation.Elbows]: true,
      [ArmorLocation.Forearms]: true,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: true,
      [ArmorLocation.ThoraxBack]: true,
      [ArmorLocation.AbdomenFront]: true,
      [ArmorLocation.AbdomenBack]: true,
      [ArmorLocation.Hips]: true,
      [ArmorLocation.Groin]: true,
      [ArmorLocation.Thighs]: true,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 33.0,
    basePrice: 990
  },
  {
    name: 'mail leggings',
    type: ArmorType.Mail,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: true,
      [ArmorLocation.Groin]: true,
      [ArmorLocation.Thighs]: true,
      [ArmorLocation.Knees]: true,
      [ArmorLocation.Calves]: true,
      [ArmorLocation.Feet]: true,
    }, baseWeight: 22.0,
    basePrice: 660
  },
  {
    name: 'mail mittens',
    type: ArmorType.Mail,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: true,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 2.0,
    basePrice: 60
  },
  {
    name: 'scale byrnie',
    type: ArmorType.Scale,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: true,
      [ArmorLocation.UpperArms]: true,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: true,
      [ArmorLocation.ThoraxBack]: true,
      [ArmorLocation.AbdomenFront]: true,
      [ArmorLocation.AbdomenBack]: true,
      [ArmorLocation.Hips]: true,
      [ArmorLocation.Groin]: true,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 30.8,
    basePrice: 440
  },
  {
    name: 'scale hauberk',
    type: ArmorType.Scale,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: true,
      [ArmorLocation.UpperArms]: true,
      [ArmorLocation.Elbows]: true,
      [ArmorLocation.Forearms]: true,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: true,
      [ArmorLocation.ThoraxBack]: true,
      [ArmorLocation.AbdomenFront]: true,
      [ArmorLocation.AbdomenBack]: true,
      [ArmorLocation.Hips]: true,
      [ArmorLocation.Groin]: true,
      [ArmorLocation.Thighs]: true,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 46.2,
    basePrice: 660
  },
  {
    name: 'scale vest',
    type: ArmorType.Scale,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: true,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: true,
      [ArmorLocation.ThoraxBack]: true,
      [ArmorLocation.AbdomenFront]: true,
      [ArmorLocation.AbdomenBack]: true,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 19.6,
    basePrice: 280
  },
  {
    name: 'plate ailettes',
    type: ArmorType.Plate,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: true,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 3.2,
    basePrice: 100
  },
  {
    name: 'plate breastplate',
    type: ArmorType.Plate,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: true,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: true,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 9.6,
    basePrice: 300
  },
  {
    name: 'plate backplate',
    type: ArmorType.Plate,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: true,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: true,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 9.6,
    basePrice: 300
  },
  {
    name: 'plate coudes',
    type: ArmorType.Plate,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: true,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 1.6,
    basePrice: 50
  },
  {
    name: 'plate great helmet',
    type: ArmorType.Plate,
    coverage: {
      [ArmorLocation.Skull]: true,
      [ArmorLocation.Face]: true,
      [ArmorLocation.Neck]: true,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 8.8,
    basePrice: 275
  },
  {
    name: 'plate greaves',
    type: ArmorType.Plate,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: true,
      [ArmorLocation.Feet]: false
    }, baseWeight: 8.0,
    basePrice: 250
  },
  {
    name: 'plate halfhelm',
    type: ArmorType.Plate,
    coverage: {
      [ArmorLocation.Skull]: true,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 3.2,
    basePrice: 100
  },
  {
    name: 'plate kneecops',
    type: ArmorType.Plate,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: true,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 2.4,
    basePrice: 75
  },
  {
    name: 'plate rerebraces',
    type: ArmorType.Plate,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: true,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 4.8,
    basePrice: 150
  },
  {
    name: 'plate vambraces',
    type: ArmorType.Plate,
    coverage: {
      [ArmorLocation.Skull]: false,
      [ArmorLocation.Face]: false,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: true,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    },
    baseWeight: 4.0,
    basePrice: 125
  },
  {
    name: 'plate 3/4 helm',
    type: ArmorType.Plate,
    coverage: {
      [ArmorLocation.Skull]: true,
      [ArmorLocation.Face]: true,
      [ArmorLocation.Neck]: false,
      [ArmorLocation.Shoulders]: false,
      [ArmorLocation.UpperArms]: false,
      [ArmorLocation.Elbows]: false,
      [ArmorLocation.Forearms]: false,
      [ArmorLocation.Hands]: false,
      [ArmorLocation.ThoraxFront]: false,
      [ArmorLocation.ThoraxBack]: false,
      [ArmorLocation.AbdomenFront]: false,
      [ArmorLocation.AbdomenBack]: false,
      [ArmorLocation.Hips]: false,
      [ArmorLocation.Groin]: false,
      [ArmorLocation.Thighs]: false,
      [ArmorLocation.Knees]: false,
      [ArmorLocation.Calves]: false,
      [ArmorLocation.Feet]: false
    }, baseWeight: 5.6,
    basePrice: 175
  }
];
